# Testing https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs
name: Test job outputs

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.message }}
    steps:
      - name: Write output
        id: step1
        run: echo "message='Hello world'" >> $GITHUB_OUTPUT
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - env:
          OUTPUT1: ${{ needs.job1.outputs.output1 }}
        name: Read output
        run: echo $OUTPUT1
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Write some message to env
        run: echo "message=Hello env" >> $GITHUB_ENV

      - name: Read message from env
        run: echo ${{ env.message }}

  upload_aarch64_wheel:    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Get wheel from CircleCI artifact
        env:
          JOB_NUMBER: 106
        run: |
          export WHEEL_PATH=$(python circleci.py artifact --job-number $JOB_NUMBER)
          echo "wheel_path=$WHEEL_PATH" >> $GITHUB_ENV