# Testing https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs
name: Test job outputs

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.message }}
    steps:
      - name: Write output
        id: step1
        run: echo "message='Hello world'" >> $GITHUB_OUTPUT

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - env:
          OUTPUT1: ${{ needs.job1.outputs.output1 }}
        name: Read output
        run: echo $OUTPUT1